{{- if .Values.ingressRoute.enabled -}}
{{- $fullName := include "jellyfin.fullname" . -}}
{{- $svcPort := .Values.service.port -}}
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "jellyfin.labels" . | nindent 4 }}
spec:
  entryPoints:
    - websecure
    routes:
  - match: Host(`minecraft.llucasshenrique.space`) && PathPrefix(`/routes`)
    kind: Rule
    services:
    - name: {{ $fullName }}
      port: 8080
  tls: 
    provider: cloudflare
  # {{- if .Values.ingressRoute.tls }}
  # tls:
  #   provider: {{ .Values.ingressRoute.tls.provider | default "default" . }}
  # {{- end }}
  # {{- if .Values.ingressRoute.routes }}
  # routes:
  # {{- range .Values.ingressRoute.routes }}
  # - match: {{ .match }}
  #   services: 
  #   - name: {{ $fullName }}
  #     port: {{ $svcPort}}
  # {{- end }}
  # {{- end }}
{{- end }}