---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-jellyfin-media-1
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  volumeName: pv-jellyfin-media-1
  resources:
    requests:
      storage: 250Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-jellyfin-media-2
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  volumeName: pv-jellyfin-media-2
  resources:
    requests:
      storage: 250Gi
  