apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-media-1
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: hostPath
  volumeName: pv-jellyfin-media-1
  resources:
    requests:
      storage: 200Gi
# ---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: pvc-jellyfin-media-2
# spec:
#   accessModes:
#     - ReadWriteOnce
#   storageClassName: local-path
#   volumeName: pv-jellyfin-media-2
#   resources:
#     requests:
#       storage: 250Gi
  