---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRouteTCP
metadata:
  name: harbor-route
spec:
  entryPoints:                 
    - websecure
  routes:                      
  - match: HostSNI(`harbor.llucasshenrique.space`)
    services:                  
    - name: harbor             
      port: 30002
  - match: HostSNI(`notary.llucasshenrique.space`)
    services:                  
    - name: harbor             
      port: 30004         
  tls:                          
    passthrough: true