---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: harbor-route
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`harbor.llucasshenrique.space`)
      kind: Rule
      services:
        - name: harbor
          port: 30002
  tls:
    provider: cloudflare
