---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: harbor-route
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`harbor.llucasshenrique.space`)
      services:
        - name: harbor-harbor-portal
          port: 80
    - match: Host(`notary.llucasshenrique.space`)
      services:
        - name: harbor-harbor-notary-server
          port: 4443
  tls:
    provider: cloudflare
