---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-jellyfin-media-1
  namespace: jellyfin
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 200Gi
  hostPath:
    type: DirectoryOrCreate
    path: /opt/disk-1/media
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - worker0
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-path
  volumeMode: Filesystem