apiVersion: v1
kind: IngressRoute
metadata:
  name: esdb-ingress
spec:
  entryPoints:
    - websecure
  routes:
  - match: Host(`esdb.llucasshenrique.space`)
    kind: Rule
    services:
    - name: eventstore-esdb
      port: 2113
  tls:
    provider: cloudflare