---
apiVersion: v1
kind: ConfigMap
metadata:
  name: config-traefik-middlewares
data:
  forwarded-real-ip.yaml: |
    middlewares:
        traefik-forwarded-real-ip:
          plugin:
            traefik-forwarded-real-ip: {}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: config-traefik-dynamic
data:
  traefik.yaml: |
    api:
      enabled: true
      insecure: true
    accesslog: true
    log:
      level: DEBUG
    providers:
      file: 
        directory: /etc/traefik/providers
        watch: true
    certificatesresolvers:
      cloudflare:
        acme:
          email: llucasshenrique@gmail.com
          storage: /etc/traefik/certs/acme.json
          dnschallenge:
            provider: cloudflare
            resolvers: 1.1.1.1:53,1.0.0.1:53
            delayBeforeCheck: 90
    experimental:
      plugins:
        traefik-forwarded-real-ip:
          moduleName: "github.com/iYUYUE/traefik-forwarded-real-ip"
          version: "v1.0.2"
