---
apiVersion: v1
kind: ConfigMap
metadata:
  name: config-traefik-middlewares
data:
  forwarded-real-ip.yaml: |
    middlewares:
        my-traefik-forwarded-real-ip:
          plugin:
            traefik-forwarded-real-ip: {}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: config-traefik-dynamic
data:
  traefik.yaml: |
    api:
      insecure: true
      dashboard: true
    accessLog: true
    entryPoints:
      traefik:
        address: ":9000"
      web:
        address: ":8000"
      websecure:
        address: ":8443"

  plugins.yaml: |
    experimental:
      plugins:
        traefik-forwarded-real-ip:
          moduleName: "github.com/iYUYUE/traefik-forwarded-real-ip"
          version: "v1.0.2"