---
apiVersion: v1
kind: ConfigMap
metadata:
  name: config-traefik-middlewares
data:
  forwarded-real-ip.yaml: |
    middlewares:
        my-traefik-forwarded-real-ip:
          plugin:
            traefik-forwarded-real-ip: {}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: config-traefik-dynamic
data:
  config.yaml: |
    api:
      insecure: true
      dashboard: true
    accessLog: true
