---
apiVersion: v1
kind: ConfigMap
metadata:
  name: config-traefik-middlewares
data:
  forwarded-real-ip.yaml: |
    middlewares:
        traefik-forwarded-real-ip:
          plugin:
            traefik-forwarded-real-ip: {}
