kind: GitRepo
apiVersion: fleet.cattle.io/v1alpha1
metadata:
  name: deployments
  namespace: fleet-local
spec:
  repo: git@github.com:llucasshenrique/omnilab-k3os
  clientSecretName: fleet-ssh
  branch: master
paths:
  - traefik