defaultNamespace: traefik
helm:
  repo: https://helm.traefik.io/traefik
  chart: traefik
  version: 9.12.3
  values:
    additionalArguments:
      - "--certificatesresolvers.cloudflare.acme.email=llucasshenrique@gmail.com"
      - "--certificatesresolvers.cloudflare.acme.storage=/data/acme.json"
      - "--certificatesresolvers.cloudflare.acme.dnschallenge=true"
      - "--certificatesresolvers.cloudflare.acme.dnschallenge.provider=cloudflare"
    envFrom:
      - configMapRef:
          name: traefik-static
      - secretRef:
          name: cloudflare-dns
      - secretRef:
          name: cloudflare-api
    additionalVolumesMounts:
      - name: traefik-dynamic-configs
        mountPath: /dynamic-config/
    additionalVolumes:
      - name: traefik-dynamic-configs
        configMap:
          - name: traefik-dynamic-configs
    resources:
      requests:
        cpu: '125m'
        memory: 128Mi
      limits:
        cpu: '500m'
        memory: 1Gi
    pilot:
      enabled: true
      token: "cf3cf80a-b07f-408a-a7c0-02fcb74ab8ee"
    experimental:
      plugins:
        traefik-forwarded-real-ip:
          moduleName: "github.com/iYUYUE/traefik-forwarded-real-ip"
          version: "v1.0.2"

kustomize:
  dir: kustomize
