defaultNamespace: traefik
helm:
  repo: https://helm.traefik.io/traefik
  chart: traefik
  version: 9.12.3
  values:
    additionalArguments:
      - "--providers.file.filename=/data/traefik.yaml"
      - "--entryPoints.websecure.http.tls.certresolver=cloudflare"
      - "--entryPoints.websecure.http.tls.domains[0].main=llucasshenrique.space"
      - "--entryPoints.websecure.http.tls.domains[0].sans=*.llucasshenrique.space"
      - "--certificatesresolvers.cloudflare.acme.email=llucasshenrique@gmail.com"
      - "--certificatesresolvers.cloudflare.acme.storage=/data/acme.json"
      - "--certificatesresolvers.cloudflare.acme.dnschallenge=true"
      - "--certificatesresolvers.cloudflare.acme.dnschallenge.provider=cloudflare"
    resources:
      requests:
        cpu: "125m"
        memory: 128Mi
      limits:
        cpu: "500m"
        memory: 1Gi
    envFrom:
      - secretRef:
          name: cloudflare-dns
      - secretRef:
          name: cloudflare-api
    volumes:
      - name: config-traefik-middlewares
        mountPath: /data/providers
        type: configMap
      - name: config-traefik-dynamic
        mountPath: /data
        type: configMap
    pilot:
      enabled: true
      token: "cf3cf80a-b07f-408a-a7c0-02fcb74ab8ee"
    experimental:
      plugins:
        enabled: true
kustomize:
  dir: kustomize
