apiVersion: apps/v1
kind: Deployment
metadata:
  name: cannapag-api-rest
spec:
  replicas: 1
  selector:
    matchLabels:
      name: cannapag-api-rest
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        name: cannapag-api-rest
    spec:
      imagePullSecrets:
        - name: harbor
        - name: harbor-rancher
      containers:
        - name: cannapag-api-rest
          image: harbor.llucasshenrique.space/cannapag/api-rest
          imagePullPolicy: Always
          envFrom:
            - secretRef:
                name: cannapag-asaas
            - secretRef:
                name: cannapag-auth0    
            - configMapRef:
                name: cannapag-api-rest-config
          ports:
            - name: http
              protocol: TCP
              containerPort: 3333
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
