---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: dev-cannapag-api-ingress
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`dev-cannapag.llucasshenrique.space`)
      kind: Rule
      services:
        - name: dev-cannapag-api
          port: 80
  tls:
    provider: cloudflare
