apiVersion: v1
kind: Service
metadata:
  name: cannapag-api-rest
spec:
  externalTrafficPolicy: Local
  selector:
    name: cannapag-api-rest
  ports:
  - name: http
    port: 3333
    targetPort: http
    
