---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-qbittorrent-config
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  volumeName: pv-qbittorrent-config
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-qbittorrent-downloads
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  volumeName: pv-qbittorrent-downloads
  resources:
    requests:
      storage: 200Gi
